import React from 'react';
import { NavLink } from 'react-router-dom';

const AdminSidebar = () => {
  return (
    <aside className="fixed left-0 top-0 h-screen w-72 bg-surface-container-lowest flex flex-col justify-between z-50 shadow-[0_1px_8px_rgba(0,0,0,0.04)]"><div className="flex flex-col"><div className="h-16 px-space-lg flex items-center gap-space-sm bg-surface-container-low"><div className="w-8 h-8 rounded-lg bg-admin-primary flex items-center justify-center text-on-admin-primary shadow-[0_0_10px_rgba(16,185,129,0.25)]"><span className="material-symbols-outlined text-[20px]">corporate_fare</span></div><div className="flex flex-col"><span className="font-headline-sm text-label-md uppercase tracking-wider text-on-surface font-bold">Grand Horizon</span><span className="font-label-sm text-label-sm uppercase tracking-widest text-admin-primary font-semibold">Resort &amp; Suites • PMS Core</span></div></div><div className="px-space-md py-space-sm"><div className="px-space-sm py-space-xs mb-space-xs font-label-sm text-label-sm uppercase text-on-surface-variant font-bold tracking-wider">Phân Hệ Tác Nghiệp</div><nav className="flex flex-col gap-space-xs">
<a href="#" onClick={(e) => e.preventDefault()} className="flex items-center gap-space-md px-space-md py-space-sm rounded-lg transition-all group text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface"><span className="material-symbols-outlined text-[20px] transition-colors">grid_view</span><span className="font-body-md text-body-md">Bàn Làm Việc</span></a>
<a href="#" onClick={(e) => e.preventDefault()} className="flex items-center gap-space-md px-space-md py-space-sm rounded-lg transition-all group text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface"><span className="material-symbols-outlined text-[20px] transition-colors">room_service</span><span className="font-body-md text-body-md">Lễ Tân & Tiền Sảnh</span></a>
<a href="#" onClick={(e) => e.preventDefault()} className="flex items-center gap-space-md px-space-md py-space-sm rounded-lg transition-all group text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface"><span className="material-symbols-outlined text-[20px] transition-colors">bedroom_parent</span><span className="font-body-md text-body-md">Quản Lý Phòng & Hạng Phòng</span></a>
<a href="#" onClick={(e) => e.preventDefault()} className="flex items-center gap-space-md px-space-md py-space-sm rounded-lg transition-all group text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface"><span className="material-symbols-outlined text-[20px] transition-colors">cleaning_services</span><span className="font-body-md text-body-md">Buồng Phòng & Kỹ Thuật</span></a>
<a href="#" onClick={(e) => e.preventDefault()} className="flex items-center gap-space-md px-space-md py-space-sm rounded-lg transition-all group text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface"><span className="material-symbols-outlined text-[20px] transition-colors">spa</span><span className="font-body-md text-body-md">Dịch Vụ & Spa</span></a>
<NavLink to="/admin" className={({ isActive }) => `flex items-center gap-space-md px-space-md py-space-sm rounded-lg transition-all group ${isActive ? 'bg-admin-primary-container text-on-admin-primary font-semibold shadow-sm' : 'text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface'}`}><span className="material-symbols-outlined text-[20px] transition-colors">restaurant</span><span className="font-body-md text-body-md">Ẩm Thực F&B & Bếp</span></NavLink>
<a href="#" onClick={(e) => e.preventDefault()} className="flex items-center gap-space-md px-space-md py-space-sm rounded-lg transition-all group text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface"><span className="material-symbols-outlined text-[20px] transition-colors">account_balance</span><span className="font-body-md text-body-md">Tài Chính & Sổ Cái</span></a>
<a href="#" onClick={(e) => e.preventDefault()} className="flex items-center gap-space-md px-space-md py-space-sm rounded-lg transition-all group text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface"><span className="material-symbols-outlined text-[20px] transition-colors">neurology</span><span className="font-body-md text-body-md">AI Concierge & Chatbot</span></a>
<a href="#" onClick={(e) => e.preventDefault()} className="flex items-center gap-space-md px-space-md py-space-sm rounded-lg transition-all group text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface"><span className="material-symbols-outlined text-[20px] transition-colors">admin_panel_settings</span><span className="font-body-md text-body-md">Quản Trị Hệ Thống</span></a>
</nav></div></div><div className="p-space-md bg-surface-container-low mx-space-sm mb-space-sm rounded-xl"><div className="flex items-center justify-between mb-space-xs"><div className="flex items-center gap-space-xs"><span className="relative flex h-2 w-2"><span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-admin-primary opacity-75"></span><span className="relative inline-flex rounded-full h-2 w-2 bg-admin-primary"></span></span><span className="font-label-sm text-label-sm text-on-surface font-semibold">Đồng Bộ PMS Core</span></div><span className="font-label-sm text-label-sm text-admin-primary font-bold uppercase tracking-wider">Trực Tiếp</span></div><div className="flex items-center justify-between text-on-surface-variant pt-space-xs font-label-sm text-label-sm"><span>Bàn giao ca trực:</span><span className="font-bold text-on-surface font-mono">02:45:18</span></div></div></aside>
  );
};

export default AdminSidebar;
